"""create incidents table

Revision ID: 3d3cf359c2a1
Revises: 
Create Date: 2026-07-07 20:41:38.883582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3cf359c2a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reporter_type', sa.Enum('citizen', 'police', 'bank', 'cyber_cell', 'other', name='reporter_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('web_portal', 'mobile_app', 'api', 'bulk_import', name='incident_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'processing', 'analyzed', 'under_investigation', 'resolved', 'closed', name='incident_status_enum'), server_default='new', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority_enum'), server_default='medium', nullable=False),
    sa.Column('scam_category', sa.Enum('digital_arrest', 'upi_fraud', 'phishing', 'qr_scam', 'identity_theft', 'investment_fraud', 'other', 'unknown', name='scam_category_enum'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI-generated fraud summary'),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('graph_node_id', sa.String(length=100), nullable=True),
    sa.Column('case_reference', sa.String(length=100), nullable=True, comment='External reference identifier (e.g., FIR, Bank Complaint ID)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name=op.f('ck_incidents_check_risk_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index('idx_incident_created', 'incidents', ['created_at'], unique=False)
    op.create_index('idx_incident_priority', 'incidents', ['priority'], unique=False)
    op.create_index('idx_incident_status', 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_graph_node_id'), 'incidents', ['graph_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_graph_node_id'), table_name='incidents')
    op.drop_index('idx_incident_status', table_name='incidents')
    op.drop_index('idx_incident_priority', table_name='incidents')
    op.drop_index('idx_incident_created', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
